# Makefile do exercicio nº7

ex07: countwords.o main.o
	gcc -g -Wall countwords.o main.o -o ex07
	
countwords.o: countwords.c
	gcc -g -Wall -c countwords.c -o countwords.o
	
main.o: main.c
	gcc -g -Wall -c main.c -o main.o
	
clean: 
	rm -f *.o ex07
	
run: ex07
	./ex07